title: 技术日志
description: 记录全栈开发的技术实践
baseurl: /wenji # the subpath of your site, e.g. /blog/
url: https://buyivi.xyz # the base hostname & protocol for your site
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: default